### ISSUE TITLE
Packwiz

### ISSUE THREAD

**Issue by Madis0** [Madis0/fabulously-optimized#28]
**Mod name**
Packwiz

**Curseforge link**

**Modrinth link**

**Other link**
https://github.com/comp500/packwiz

**What it does**
Makes MultiMC pack autoupdate, vanilla launcher support in the future

**Why should it be in the modpack**
Updates are good, vanilla installer is planned

**Why shouldn't it be in the modpack**
Setup may complicate things, especially when I update the pack

**Categories**

- [ ] Performance optimization
- [ ] Graphics optimization
- [ ] New feature
- [ ] Optifine parity
- [x] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details**

**Todo**
- [x] Make sure CF is fine with it [(yes, it's on their spreadsheet)](https://docs.google.com/spreadsheets/d/176Wv-PZUo9hFxy6oC6N8tWdquBLPRtSuLbNK-r0_byM/edit#gid=1212240442)
- [x] Release the MultiMC pack files
- [x] Mimic normal MultiMC version in name and manifest
- [x] Restructure configs to reduce duplicates
- [x] See how/if Hydrogen works
- [ ] Add vanilla launcher support

**Comment by Madis0** [comment]
Going to wait until it gets the promised rewrite, seems a bit unstable for now.

**Comment by TheMadHau5** [comment]
Mod seems stable, why not add?

**Comment by Madis0** [comment]
Not quite, there are still some problems like replacing Fabric mods with Forge ones and not seeing some updates for the mods.

**Comment by Madis0** [comment]
Currently distributed as a GH-exclusive experiment. 
Considered uploading to Curseforge as well, but that would require updates to stay on top and pack updates (unlike mod list updates) are rarely needed for this.
