### ISSUE TITLE
1.17.1 plan

### ISSUE THREAD

**Issue by Madis0** [Madis0/fabulously-optimized#59]
1.17 is released. This is the approximate to-do list for a stable version of the pack:

- [x] 1.17 Fabric #35, no Jumploader
- [x] Several of the mods should work
- [x] Canvas as a temporary Sodium replacement
- [x] Some alternative zoom mod
- [x] Options.txt #30 
- [x]  #25
- [x] Packwiz for MultiMC #28 
- [x] Enable LDL entities again 
- [x] Revert the FOV change + wiki
- [x] ~~Readjust Canvas and Smooth lighting~~
- [x] Majority of the mods or equivalents updated
 - [x] Sodium update in CF [(0.2?)](https://github.com/CaffeineMC/sodium-fabric/issues/674)
- [x] Iris #12
- [x] Update shader wiki
- [x] Update controls wiki
- [x] #82 
- [x] Update the mod list and this time add authors as well
- [x] 1.17.1 released by Mojang
- [x] 1.17.1 available in CF Launcher
- [x] FerriteCore
- [x] Maybe #76 
- [x] Semver (x.x.x-alpha.x)
- [x] Enable Cull Leaves by default
- [x] Update Hydrogen
- [x] 2.0.0b4 parity (Iris again)
- [x] Re-evaluate Custom Fog (works under lava? works at all with SodExt? server-side stuff?)
- [x] #102 
- [x] Test Indium performance
- [x] Review packwiz py script, make sure all mods are removed before adding from CF
- [x] Add more Indium-compatible mods
- [x] Review, which config libraries are actually needed
- [x] 1.9.1 parity (where feasible)
- [x] CF bugfix (smooth upgrade from 1.17 -> 1.17.1)
- [x] **Sodium bugfix update** (and Iris to go along with it)
- [x] AdvancementInfo and Better Mount HUD (will be added for release)

**Comment by technicaldiff** [comment]
sodium has a 1.17 dev branch which  works fine

**Comment by Madis0** [comment]
@technicaldiff That's great, but I cannot use it in CF unless they decide to publish it.

**Comment by technicaldiff** [comment]
> @technicaldiff That's great, but I cannot use it in CF unless they decide to publish it.

https://github.com/CaffeineMC/sodium-fabric/issues/674
according to jellysquid it should hopefully be in a week

**Comment by ttmx** [comment]
@technicaldiff Which commit are you using?
Thx

**Comment by technicaldiff** [comment]
@ttmx  https://github.com/Kroppeb/sodium-fabric/actions/runs/919555548 
this one

**Comment by Rajbir98** [comment]
plz publish 1.17 version or i have to stay on 1.16.5 plz update soon
i wish sodium will update too i am satisfied of your work.

**Comment by Madis0** [comment]
@Rajbir98 I already did publish the first beta yesterday, check the Files tab on CF.

**Comment by TheMadHau5** [comment]
Why was OK Zoomer replaced with WI Zoom?

**Comment by Madis0** [comment]
@TheMadHau5

1. It doesn't exist for 1.17 stable
2. It has future plans about "letting servers disable some parts of the mod". It is a bit confusing for now - will see if and how they will do it. But if it does happen, I will replace it for good because I don't like the idea of giving servers more control than actually needed.

**Comment by wafflecoffee** [comment]
> That's great, but I cannot use it in CF unless they decide to publish it.

@Madis0 In overrides, you could include a compiled version of Kroppeb's fork of Sodium [here](https://github.com/Kroppeb/sodium-fabric/tree/1.17.x/next). The license permits redistribution in this regard, so long as a copy of the license is included, and it links back to the GH repo somewhere somewhat noticeable. (I'm not even sure if the latter part is necessary, but I would do so just to be safe anyway.)

**Comment by Madis0** [comment]
> > That's great, but I cannot use it in CF unless they decide to publish it.
> 
> @Madis0 In overrides, you could include a compiled version of Kroppeb's fork of Sodium [here](https://github.com/Kroppeb/sodium-fabric/tree/1.17.x/next). The license permits redistribution in this regard, so long as a copy of the license is included, and so long as there is a link back to the GH repo somewhere that's somewhat noticeable. (I'm not even sure if the latter part is necessary, but I would do so just to be safe anyway.)

I don't know, few months back (I think it was for 1.16.3) I tried uploading a version with a custom-compiled Sodium and it got rejected.

**Comment by technicaldiff** [comment]
> > > That's great, but I cannot use it in CF unless they decide to publish it.
> > 
> > 
> > @Madis0 In overrides, you could include a compiled version of Kroppeb's fork of Sodium [here](https://github.com/Kroppeb/sodium-fabric/tree/1.17.x/next). The license permits redistribution in this regard, so long as a copy of the license is included, and so long as there is a link back to the GH repo somewhere that's somewhat noticeable. (I'm not even sure if the latter part is necessary, but I would do so just to be safe anyway.)
> 
> I don't know, few months back (I think it was for 1.16.3) I tried uploading a version with a custom-compiled Sodium and it got rejected.

secondly kroppebs fork has actually a pr open in jelly squids sodium and is pending merge and i tried his forks sodium with the pack and its much much better than canvas

**Comment by Madis0** [comment]
https://support.overwolf.com/en/support/solutions/articles/9000197913-non-curseforge-mods

> It can take several days for a review to occur, but once it has you will be notified with either a message declining the addition or approving it along with any information as to why or why not. 
>
> If a specific version of a CurseForge-hosted mod is not on the site, this means the author has chosen not to upload it for some reason. These versions are not allowed to be included in modpacks.

**Comment by wafflecoffee** [comment]
typical curseforge, thinking that everything has to go through them...

**Comment by Madis0** [comment]
I think it actually makes sense:
* JARs could easily include malware, additional checks for non-CF versions waste CF-s time to review
* Non-CF JARs don't increase the developers' mods' download count, which doesn't help with getting rewards or increasing popularity of the mods
* Developers could get annoyed when modpacks publish development versions (and they get the crash reports/issues regarding those) or maybe even stolen/modded versions of some ARR mods

**Comment by technicaldiff** [comment]
makes sense...how about publishing it in github and then when jelly squid releses pushing it to CF

**Comment by Madis0** [comment]
> makes sense...how about publishing it in github and then when jelly squid releses pushing it to CF

That fragments the download locations, making life more complicated for me, the modders and the users (see the points I posted above), so unfortunately that's a no. But as always, I do encourage my users to [use more mods than there are in the pack](https://github.com/Madis0/fabulously-optimized/wiki/Adding-more-mods).

**Comment by Rajbir98** [comment]
i want to download sodium 1.17.Dev how could i download it

**Comment by piosrunix** [comment]
any idea when you guys will release this update?

**Comment by Madis0** [comment]
> any idea when you guys will release this update?

I'll mark the version as stable when Sodium is stable enough and parity with 1.16.5 version has been reached.

**Comment by Gavins38** [comment]
Sodium Extras has released for 1.17.1 same with sodium 1.17.1

**Comment by Madis0** [comment]
@Gavins38 Thanks. Regarding Starlight: #21

**Comment by Gavins38** [comment]
> @Gavins38 Thanks. Regarding Starlight: #21

Ty for updating but uh i think theres some serious visual bugs
https://github.com/Madis0/fabulously-optimized/issues/96.

**Comment by Rajbir98** [comment]
Sodium has messed up many things this time causing visual bugs and performance drop

**Comment by wafflecoffee** [comment]
@Rajbir98 You're probably either using old AMD or Intel drivers on Windows, in which case the bugs are known but extremely hard for the Sodium devs to fix

**Comment by Rajbir98** [comment]
its true i am on legacy driver

**Comment by Rajbir98** [comment]
sodium devs is still working hard towards legacy driver users https://github.com/CaffeineMC/sodium-fabric/actions/runs/1062321084 heres the latest build action

**Comment by Rajbir98** [comment]
i think they are tring to fix it

**Comment by lebestnoob** [comment]
Iris now has support for 1.17.1. The latest version is available on the projects GitHub release page. Will it be included?
[Download](https://github.com/IrisShaders/Iris/releases/tag/1.1.1)

**Comment by Madis0** [comment]
2.1.0 has been released!
