### ISSUE TITLE
Explain Packwiz

### ISSUE THREAD

**Issue by Madis0** [Madis0/fabulously-optimized#82]
A wiki page for Packwiz

- [x] What it is
- [x] How does it work
- [x] How to install
- [x] Why is it not in CF (update need, author support, experimental)
- [x] What to do when MC upgrades
- [x] #81

**Comment by Madis0** [comment]
https://github.com/Madis0/fabulously-optimized/wiki/Auto-updating-MultiMC-pack
