### ISSUE TITLE
Release schedule wiki

### ISSUE THREAD

**Issue by Madis0** [Madis0/fabulously-optimized#90]
- [x] Copy info from changelog page
- [x] What happens if MC updates
- [x] Auto-updating multimc link
- [x] ViaFabric/Multiconnect info
- [x] Link to in CF and changelog

**Comment by Madis0** [comment]
https://github.com/Madis0/fabulously-optimized/wiki/Version-support-FAQ
